#!/bin/bash

# This is a bash script for interacting with the various files in './scripts/'.
# 
# Usage: ./bdocs [option]

set -e

# The project's root directory.
export PROJECT_ROOT
PROJECT_ROOT="$(dirname "$(realpath "$0")")"

# Displays usage for bdocs
display_help() {
    cat << EOF
bdocs is a CLI tool for executing Braze Docs scripts.

USUAGE:
  ./bdocs [option]

OPTIONS:
  deploy       Create the deploy body text for weekly deployments
  release      Create the release body text for monthly releases
  transform    Transform reference links to inline links on 1 or more pages
  clean        Remove reference links that are not being used on 1 or more pages
  help         Display this help message and exit

EOF
}

# Check if no arguments were provided
if [[ $# -eq 0 ]]; then
    display_help
    exit 1
fi

# Argument parsing
case $1 in
    deploy)
        if [[ $# -eq 3 ]]; then
            "$PROJECT_ROOT/scripts/deploy_text.sh" "$2" "$3"
        else
            "$PROJECT_ROOT/scripts/deploy_text.sh"
        fi
        ;;
    release)
        "$PROJECT_ROOT/scripts/release_text.sh"
        ;;
    transform)
        if [[ -z "$2" ]]; then
            echo "Error: The path to file or directory is required."
            exit 1
        fi
        python3 "$PROJECT_ROOT/scripts/convert_reference_links.py" "$2"
        ;;
    clean)
        if [[ -z "$2" ]]; then
            echo "Error: The path to file or directory is required."
            exit 1
        fi
        ruby "$PROJECT_ROOT/scripts/remove_unused_reference_links.rb" "$2"
        ;;
    help)
        display_help
        ;;
    *)
        echo "Invalid option: $1. To see all options, run: ./bdocs help"
        exit 1
        ;;
esac
