#!/bin/bash

# DESCRIPTION.

set -e

# The project's root directory. Only accessible through git.
export PROJECT_ROOT
PROJECT_ROOT="$(dirname "$(realpath "$0")")"

# Displays usage for bdocs
display_help() {
    cat << EOF
bdocs - todo add description.

Usage: ./bdocs [option]

Options:
  deploy       Create deploy text
  release      Create release text
  clinks       Convert all reference links to in-line links
  rlinks       Remove all unused reference links
  help         Display this help message and exit

EOF
}

# Check if no arguments were provided
if [[ $# -eq 0 ]]; then
    display_help
    exit 1
fi

# Argument parsing
case $1 in
    deploy)
        if [[ $# -eq 3 ]]; then
            "$PROJECT_ROOT/scripts/deploy_text.sh" "$2" "$3"
        else
            "$PROJECT_ROOT/scripts/deploy_text.sh"
        fi
        ;;
    release)
        "$PROJECT_ROOT/scripts/release_text.sh"
        ;;
    clinks)
        if [[ -z "$2" ]]; then
            echo "Error: Path is required."
            exit 1
        fi
        python3 "$PROJECT_ROOT/scripts/convert_reference_links.py" "$2"
        ruby "$PROJECT_ROOT/scripts/remove_unused_reference_links.rb" "$2"
        ;;
    rlinks)
        if [[ -z "$2" ]]; then
            echo "Error: Path is required."
            exit 1
        fi
        ruby "$PROJECT_ROOT/scripts/remove_unused_reference_links.rb" "$2"
        ;;
    help)
        display_help
        ;;
    *)
        echo "Invalid option: $1. To see all options, run: ./bdocs help"
        exit 1
        ;;
esac
