#!/usr/bin/env python3

# Uses 'git diff' to track renamed files or directories, then creates redirects 
# in 'assets/js/broken_redirect_list.js'. Note that redirects are only created 
# for renamed files if they're 'committed', not just 'added' to the branch.
#
# Usage: ./bdocs mredirects

import os
import re
import subprocess

# Global variables
PROJECT_ROOT = os.environ.get('PROJECT_ROOT')
REDIRECT_FILE = os.environ.get('REDIRECT_FILE')
LOG_PATH = os.path.join(PROJECT_ROOT, "scripts", "temp", "mredirect_logs")

# Uses Git to return a list of renamed files and directories in this format:
#   files:       rename _docs/_contributing/{bdocs.md => test.md} (100%)
#   directories: rename _docs/_contributing/{yaml => jekyll}/metadata.md (100%)
def get_renamed_files():
    import pathlib, subprocess, os

    # resolve upstream of current branch and fetch just that ref
    res = subprocess.run(
        ["git", "rev-parse", "--abbrev-ref", "--symbolic-full-name", "@{upstream}"],
        capture_output=True, text=True
    )
    if res.returncode != 0 or not res.stdout.strip():
        raise RuntimeError("No upstream set for current branch. Run `git push -u origin <branch>`.")

    upstream_ref = res.stdout.strip()
    remote, remote_branch = upstream_ref.split("/", 1)
    subprocess.run(["git", "fetch", "--quiet", remote, remote_branch, "develop"], check=False)

    repo_root = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"], capture_output=True, text=True, check=True
    ).stdout.strip()
    docs_rel = str(pathlib.Path(repo_root, "_docs").relative_to(repo_root))

    # full PR range: base...upstream
    cmd = [
        "git", "diff", "-M", "--summary", "--diff-filter=R",
        "origin/develop..."+upstream_ref, "--", docs_rel
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)

    return [
        line.strip() for line in result.stdout.splitlines()
        if line.lstrip().startswith("rename")
    ]


# Adds unmatched lines to ./scripts/temp/mredirect_logs.
def log_unmatched(line):
    os.makedirs(os.path.dirname(LOG_PATH), exist_ok=True)
    with open(LOG_PATH, "a") as log_file:
        log_file.write(line + "\n")


# Creates redirects by cleaning up the list generated by 'get_renamed_files'.
def create_redirect(line):
    original_line = line.strip()

    # strip leading 'rename' and trailing '(NN%)'
    line = line.split(" ", 1)[1]
    line = re.sub(r"\s\(\d+%\)$", "", line)

    # allow empty old/new inside braces
    m = re.search(r"{([^}]*)\s=>\s([^}]*)}", line)
    if not m:
        log_unmatched(original_line)
        return None

    old_part, new_part = m.group(1), m.group(2)

    prefix = line.split("{", 1)[0].strip()
    suffix = line.split("}", 1)[1].strip()

    def norm(p):
        # strip extension
        p = p.replace(".md", "")
        # collapse multiple slashes and enforce leading slash
        p = re.sub(r"//+", "/", "/"+p.lstrip("/"))
        # drop underscore only at the beginning of a segment
        p = re.sub(r"/_+", "/", p)
        return p.rstrip("/")

    url_old = norm(f"{prefix}{old_part}{suffix}")
    url_new = norm(f"{prefix}{new_part}{suffix}")

    return f"validurls['{url_old}'] = '{url_new}';"


# Remove duplicate lines while preserving single blank lines
def remove_duplicates(lines):
    unique_lines = []
    double_blank = False

    for line in lines:
        if line.strip() == "":          
            if not double_blank:         
                unique_lines.append(line)
                double_blank = True
        else:                           
            double_blank = False
            if line not in unique_lines:
                unique_lines.append(line)

    return unique_lines


def main():
    # Reset the log file each run
    os.makedirs(os.path.dirname(LOG_PATH), exist_ok=True)
    with open(LOG_PATH, "w"):
        pass

    changed_files = get_renamed_files()
    if not changed_files:
        return

    placeholder_comment = "// validurls['OLD'] = 'NEW';"
    redirects_created = False

    with open(REDIRECT_FILE, "r+") as f:
        original_lines = f.readlines()
        lines = [l for l in original_lines if l.strip() != placeholder_comment]

        # Build redirects, skip duplicates
        for line in changed_files:
            redirect_line = create_redirect(line)
            if redirect_line and (redirect_line + "\n") not in lines:
                lines.append(redirect_line + "\n")
                redirects_created = True

        if not redirects_created:
            print(
                "Error: Git can't find any renamed files committed in this branch.\n"
                "Note that redirects are only created for renamed files if they're "
                "'committed', not just 'added' to the branch."
            )
            return

        # Add placeholder and tidy file
        lines.append(f"\n{placeholder_comment}\n")
        unique_lines = remove_duplicates(lines)

        # Only write if content actually changed
        if unique_lines != original_lines:
            f.seek(0)
            f.truncate()
            f.writelines(unique_lines)
            print("Redirects created successfully!")
            if os.path.getsize(LOG_PATH) > 0:
                with open(LOG_PATH) as log_file:
                    print("\nHowever, some redirects will need to be created manually:\n")
                    print(log_file.read().rstrip())


if __name__ == "__main__":
    main()
