# Site settings
title: Braze Documentation
email: success@braze.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to Braze Documentation. Braze provides a comprehensive user engagement solution for your mobile apps.
baseurl: "/docs/es" # the subpath of your site, e.g., /blog
homeurl: "https://www.braze.com" # the base hostname & protocol for your site, e.g., http://example.com
twitter_username: Braze
github_username:  braze-inc

language: es

destination: _site/docs/es

# Source dir
source: '.'

# GitHub config
github_baseurl: 'https://github.com/braze-inc/braze-docs/blob/develop/_lang/es/'

# Collections directory
collections_dir: _lang/es/


collections:
  home:
    title: Documentation
  user_guide:
    title: Guía del usuario
  developer_guide:
    title: Guía del desarrollador
  api:
    title: API
    default_nav_url: basics/
  partners:
    title: Socios tecnológicos
  help:
    title: Ayuda
  hidden: # Hidden pages not directly linked via navigation
    title: Braze
  docs_pages: # Site specific pages. ie main redirects and search
    title: Braze


# Image asset pipeline setting for japr
asset_pipeline:
  display_path: docs/es/assets

# Algolia Search index
algolia:
  index_name: "DocSearch_Spanish"
  files_to_exclude:
    - _lang/es/_hidden/*
    - _lang/es/_hidden/*/* #exclude hidden subdirectories from indexing
    - _lang/es/_hidden/*/*/* #exclude additional hidden subdirectories from indexing
    - _lang/es/_docs_pages/*
    - _lang/es/_docs_pages/*/* #exclude hidden subdirectories from indexing
    - _lang/es/_docs_pages/*/*/* #exclude additional hidden subdirectories from indexing
    - _lang/es/_home/Styling_Test_Page.md
