# Site settings
title: Braze Documentation
email: success@braze.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to Braze Documentation. Braze provides a comprehensive user engagement solution for your mobile apps.
baseurl: "/docs/fr" # the subpath of your site, e.g., /blog
homeurl: "https://www.braze.com" # the base hostname & protocol for your site, e.g., http://example.com
twitter_username: Braze
github_username:  braze-inc

language: fr

destination: _site/docs/fr

# Source dir
source: '.'

# GitHub config
github_baseurl: 'https://github.com/braze-inc/braze-docs/blob/develop/_lang/fr/'

# Collections directory
collections_dir: _lang/fr_fr/


collections:
  home:
    title: Documentation
  user_guide:
    title: Guide de l’utilisateur
  developer_guide:
    title: Guide du développeur
  api:
    title: API
    default_nav_url: basics/
  partners:
    title: Technology Partners
  help:
    title: Aide
  hidden: # Hidden pages not directly linked via navigation
    title: Braze
  docs_pages: # Site specific pages. ie main redirects and search
    title: Braze


# Image asset pipeline setting for japr
asset_pipeline:
  display_path: docs/fr/assets

# Algolia Search index
algolia:
  index_name: "DocSearch_French"
  files_to_exclude:
    - _lang/fr/_hidden/*
    - _lang/fr/_hidden/*/* #exclude hidden subdirectories from indexing
    - _lang/fr/_hidden/*/*/* #exclude additional hidden subdirectories from indexing
    - _lang/fr/_docs_pages/*
    - _lang/fr/_docs_pages/*/* #exclude hidden subdirectories from indexing
    - _lang/fr/_docs_pages/*/*/* #exclude additional hidden subdirectories from indexing
    - _lang/fr/_home/Styling_Test_Page.md
