# Blocks merging of pull requests based on certain conditions, such as a 'status: do not merge' label.
name: "Block Merging"

on:
  pull_request:
    types: [labeled, unlabeled] # Triggers only when labels are added or removed.

jobs:
  block-do-not-merge-label:
    name: "Check for lable: 'status: do not merge'"
    runs-on: ubuntu-latest
    steps:
      - name: "Fail if label is present"
        run: |
          LABELS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "${{ github.event.pull_request.issue_url }}/labels" | jq -r '.[].name')

          if echo "$LABELS" | grep -q "^status: do not merge$"; then
            echo "A 'status: do not merge' label was found. Merging will be blocked until it's removed."
            exit 1
          fi
