# Blocks merging of pull requests based on certain conditions, such as a 'do not merge' label.
name: "Block Merge"

on:
  pull_request:    
    # Add more types if needed, but only the minimum required for each job in the workflow.
    types: [opened, synchronize, labeled, unlabeled]

# Allows this to run on forked pull requests.
permissions:
  contents: read
  pull-requests: read

# If needed, add additional jobs for blocking merges here.
jobs:
  block-do-not-merge-label:
    name: "Check for 'do not merge' label"
    runs-on: ubuntu-latest
    steps:
      - name: "Check labels"
        run: |
          if echo "${{ toJson(github.event.pull_request.labels.*.name) }}" | grep -q '"do not merge"'; then
            echo "'do not merge' label found. Merging is blocked until removed."
            exit 1
          else
            echo "No 'do not merge' label found. Check passed."
            exit 0
          fi
          
