name: Translation tasks

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  translation-tasks:
    # Run only for i18n branches to save minutes
    if: startsWith(github.head_ref, 'i18n_phrase-')
    runs-on: ubuntu-latest
    steps:
      - name: Rename title and add label
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const branch = pr.head.ref;
            core.info(`Branch: ${branch}`);

            // 1) Guard label
            const hasLabel = (pr.labels || []).some(l => l.name === 'phrase-translation');
            if (hasLabel) {
              core.info('Skip: label already present.');
              return;
            }

            // 2) Parse i18n_phrase-<lang>-<YYYYMMDD>
            const m = branch.match(/^i18n_phrase-([a-z_]+)-(\d{8})$/i);
            if (!m) {
              core.info(`Skip: branch pattern not matched: ${branch}`);
              return;
            }
            const lang = m[1];
            const y = m[2].slice(0,4);
            const mo = m[2].slice(4,6);
            const d = m[2].slice(6,8);

            const date = new Date(Date.UTC(+y, +mo - 1, +d));
            const months = ['January','February','March','April','May','June','July','August','September','October','November','December'];
            const pretty = `${months[date.getUTCMonth()]} ${date.getUTCDate()}, ${date.getUTCFullYear()}`;
            const newTitle = `Phrase translations for '${lang}' ${pretty}`;

            // 3) Update title
            if (pr.title !== newTitle) {
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                title: newTitle
              });
              core.info(`Title set: ${newTitle}`);
            } else {
              core.info('Title already correct.');
            }

            // 4) Add label
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              labels: ['phrase-translation']
            });
            core.info('Label added.');
